# Generated by Django 5.1.1 on 2024-10-08 01:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageProcessor', '0002_alter_uploadimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimage',
            old_name='image',
            new_name='imageUpload',
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='imageFiltered',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='processedImage/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='uploadedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
