# Generated by Django 5.1.1 on 2024-10-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageProcessor', '0003_rename_image_uploadimage_imageupload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadedImage', models.ImageField(upload_to='uploads/')),
                ('filteredImage', models.ImageField(upload_to='processedImage/')),
                ('uploadedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='uploadImage',
        ),
    ]
