# Generated by Django 5.1.1 on 2024-10-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageProcessor', '0004_image_delete_uploadimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filteredImage',
            field=models.ImageField(blank=True, null=True, upload_to='processedImage/'),
        ),
    ]
