# Generated by Django 5.1.1 on 2024-10-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageProcessor', '0005_alter_image_filteredimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageTable',
        ),
    ]
